# Generated by Django 4.1 on 2022-09-06 18:03

from django.db import migrations, models
import lanarce_portfolio.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=lanarce_portfolio.images.models.get_file_upload_path),
        ),
    ]
