# Generated by Django 4.1 on 2022-09-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(default=None, help_text='Image', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='images.image'),
            preserve_default=False,
        ),
    ]
